from app.core.exceptions import AppError
from app.llm.base import LLMProvider
from app.rag.models import ChatResponse, SourceResponse
from app.rag.prompts import build_rag_prompt
from app.retrieval.models import RetrievedChunk
from app.retrieval.service import RetrievalService


class RAGService:
    """Retrieval-Augmented Generation service."""

    # Limit the amount of text sent from each retrieved chunk.
    MAX_CHUNK_CHARS = 1500

    # Limit the amount of text generated by the LLM.
    MAX_OUTPUT_TOKENS = 100

    def __init__(
        self,
        retrieval_service: RetrievalService,
        llm_provider: LLMProvider,
    ) -> None:
        self.retrieval_service = retrieval_service
        self.llm_provider = llm_provider

    async def answer(
        self,
        question: str,
        top_k: int = 5,
    ) -> ChatResponse:
        """Retrieve relevant context and generate an answer."""

        question = question.strip()

        if not question:
            raise AppError(
                status_code=400,
                code="INVALID_QUESTION",
                message="Question cannot be empty.",
            )

        retrieved_chunks = self.retrieval_service.retrieve(
            query=question,
            top_k=top_k,
        )

        context = self._build_context(
            retrieved_chunks,
        )

        prompt = build_rag_prompt(
            question=question,
            context=context,
        )

        result = await self.llm_provider.generate(
            prompt,
            temperature=0.2,
            max_tokens=self.MAX_OUTPUT_TOKENS,
        )

        sources = [
            SourceResponse(
                chunk_id=item.chunk.chunk_id,
                title=item.chunk.title,
                guest=item.chunk.guest,
                date=item.chunk.date,
                source_url=item.chunk.source_url,
                score=item.score,
            )
            for item in retrieved_chunks
        ]

        return ChatResponse(
            provider=result.provider,
            model=result.model,
            response=result.content,
            sources=sources,
        )

    @classmethod
    def _build_context(
        cls,
        retrieved_chunks: list[RetrievedChunk],
    ) -> str:
        """Convert retrieved chunks into bounded LLM context."""

        if not retrieved_chunks:
            return "No relevant transcript context was found."

        sections: list[str] = []

        for index, item in enumerate(
            retrieved_chunks,
            start=1,
        ):
            chunk = item.chunk

            chunk_text = chunk.text.strip()

            # Prevent very large transcript chunks from making
            # the final RAG prompt excessively large.
            if len(chunk_text) > cls.MAX_CHUNK_CHARS:
                chunk_text = (
                    chunk_text[: cls.MAX_CHUNK_CHARS]
                    + "\n[Transcript truncated]"
                )

            section = f"""
SOURCE {index}

Title: {chunk.title}
Guest: {chunk.guest or "Unknown"}
Date: {chunk.date or "Unknown"}
URL: {chunk.source_url or "N/A"}

Transcript:
{chunk_text}
""".strip()

            sections.append(section)

        return "\n\n".join(sections)